/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorialsIndexRouteImport } from './routes/tutorials/index'
import { Route as TutorialsTutorialIdRouteImport } from './routes/tutorials/$tutorialId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsIndexRoute = TutorialsIndexRouteImport.update({
  id: '/tutorials/',
  path: '/tutorials/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsTutorialIdRoute = TutorialsTutorialIdRouteImport.update({
  id: '/tutorials/$tutorialId',
  path: '/tutorials/$tutorialId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tutorials/$tutorialId': typeof TutorialsTutorialIdRoute
  '/tutorials': typeof TutorialsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tutorials/$tutorialId': typeof TutorialsTutorialIdRoute
  '/tutorials': typeof TutorialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tutorials/$tutorialId': typeof TutorialsTutorialIdRoute
  '/tutorials/': typeof TutorialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tutorials/$tutorialId' | '/tutorials'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tutorials/$tutorialId' | '/tutorials'
  id: '__root__' | '/' | '/tutorials/$tutorialId' | '/tutorials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TutorialsTutorialIdRoute: typeof TutorialsTutorialIdRoute
  TutorialsIndexRoute: typeof TutorialsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials/': {
      id: '/tutorials/'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof TutorialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials/$tutorialId': {
      id: '/tutorials/$tutorialId'
      path: '/tutorials/$tutorialId'
      fullPath: '/tutorials/$tutorialId'
      preLoaderRoute: typeof TutorialsTutorialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TutorialsTutorialIdRoute: TutorialsTutorialIdRoute,
  TutorialsIndexRoute: TutorialsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
