name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCOUNT_ID: 305870070165
      AWS_REGION: eu-west-2
      ECR_REPO: main
      IMAGE_TAG: esc
      TRANSCRIBE_IMAGE_TAG: transcribe
      STATUS_IMAGE_TAG: statuses
      LLM_IMAGE_TAG: llm

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region:  eu-west-2


    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

    # Build and push docker image for backend lambda
    - name: Build and Push backend Lambda
      run: |
        cd backend
        docker build -t $AWS_ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/$ECR_REPO:$IMAGE_TAG .
        docker push $AWS_ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/$ECR_REPO:$IMAGE_TAG

    # Build and push docker image for transcription
    - name: Build and Push transcription lambda
      run: |
        cd workflow/transcribe
        docker build -t $AWS_ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/$ECR_REPO:$TRANSCRIBE_IMAGE_TAG .
        docker push $AWS_ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/$ECR_REPO:$TRANSCRIBE_IMAGE_TAG


    - name: Build and Push status updater lambda
      run: |
        cd workflow/StatusUpdater
        docker build -t $AWS_ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/$ECR_REPO:$STATUS_IMAGE_TAG .
        docker push $AWS_ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/$ECR_REPO:$STATUS_IMAGE_TAG


    - name: Build and Push llm lambda
      run: |
        cd workflow/ContentGenerator
        docker build -t $AWS_ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/$ECR_REPO:$LLM_IMAGE_TAG .
        docker push $AWS_ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/$ECR_REPO:$LLM_IMAGE_TAG


    - name: Export TF_VAR for Terraform
      run: |
        echo "TF_VAR_backend_image_tag=${IMAGE_TAG}" >> $GITHUB_ENV
        echo "TF_VAR_mongodb_uri=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV
        echo "TF_VAR_mongodb_db=${{ secrets.MONGODB_DB }}" >> $GITHUB_ENV
        echo "TF_VAR_mongodb_collection=${{ secrets.MONGODB_COLLECTION }}" >> $GITHUB_ENV
        echo "TF_VAR_transcibe_image_tag=${{ env.TRANSCRIBE_IMAGE_TAG }}" >> $GITHUB_ENV
        echo "TF_VAR_assemblyai_api_key=${{ secrets.ASSEMBLYAI_API_KEY }}" >> $GITHUB_ENV
        echo "TF_VAR_status_image_tag=${{ env.STATUS_IMAGE_TAG }}" >> $GITHUB_ENV
        echo "TF_VAR_llm_image_tag=${{ env.LLM_IMAGE_TAG }}" >> $GITHUB_ENV
        echo "TF_VAR_gemini_api_key=${{ secrets.GEMINI_API_KEY }}" >> $GITHUB_ENV

    # Terraform deployment
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.0

    - name: Terraform Init
      run: |
        terraform init -backend-config="bucket=configs-305870070165"
      working-directory: ./infra

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./infra

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./infra

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./infra
